# Generated by Django 6.0.2 on 2026-05-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='commissions.consultor')),
            ],
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, unique=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_nota', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='commissions.comissao')),
            ],
        ),
    ]
